<?php

namespace Tests\Feature;

use Mockery\Mock;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

use App\User;
use Mockery;

class LocationTest extends TestCase
{

    /**
     * @param Mock $repositoryMock 假裝的repository
     *
     */
    protected $repositoryMock = null;

    /**
     *  test edit location view whether locations vairable exist or not
     *
     * @return void
     */
     public function testLocationList()
     {
         // 驗證登入
         $user = new User(array('email' => 'garyng@gmail.com'));
         $this->be($user); //You are now authenticated

         // 嘗試 get 網址
         $response = $this->call('GET','/edit_location');

         $response->assertStatus(200);

         // 判斷 views 裡是否有 locations 變數
         $response->assertViewHas('locations');
     }

     public function testAddLocation()
     {

     }

     public function tearDown()
     {
         parent::tearDown(); // TODO: Change the autogenerated stub
         // 每次 test case 結束後要清掉假物件
         Mockery::close();
     }
}
